#!/bin/bash
MEMBERS=("member1 member2 member3") # assign users of this image-container, NO comma between member name

WORKDIR="/home/workspace" # code-dir that will be shown on container
DATADIR="/home/data"      # data-dir that will be shown on container

IMAGE_NAME="image-name" # name the image that will be built
IMAGE_TAG="test"         # tag of the image that will be built
CONTAINER_NAME="container-name"  # name the container that will be deployed ex) <purpose>_<detail>_<user>
USER="member1" # name the container owner
GPUS='"device=n"' # assign gpu device

PROJECT_REPO_DIR="path of code directory" # absolute path for code folder
PROJECT_DATA_DIR="path for data directory" # absolute path for data folder

REMOVE_ON_END=true # if true, the container will be automatically removed when you exit from container or container finished the command you put on docker run
